# from constant_apparent_power_model_changes import ConstantApparentPowerModelApparentPowerInjectionChange
from kuramoto_oscillator_model_perturbations import KuramotoOscillatorModelNaturalFrequencyPerturbation
from perturbation import Perturbation
