from dynamic_models import StructurePreservingSynchronousGeneratorModel
from .model import Model
from static_models import ConstantApparentPowerModel, ConstantVoltageMagnitudeRealPowerModel, StaticModel